#define EnableDlgItem(hwnd,ID,enable) EnableWindow(GetDlgItem(hwnd,ID),enable)
#define ShowDlgItem(hwnd,ID,flag) ShowWindow(GetDlgItem(hwnd,ID),flag)
#define SetDlgItemFont(hwnd,ID,font) SetWindowFont(GetDlgItem(hwnd,ID),font,TRUE)

#define StatusBar_SetParts(status,partsCount,parts) SNDMSG(status,SB_SETPARTS,partsCount,(LPARAM)parts)
#define StatusBar_SetText(status,part,text) SNDMSG(status,SB_SETTEXT,part,(LPARAM)text)
#define StatusBar_SetIcon(status,part,icon) SNDMSG(status,SB_SETICON,part,(LPARAM)icon)

#define Rebar_GetBandCount(rebar) SNDMSG(rebar,RB_GETBANDCOUNT,0,0)
#define Rebar_IDToIndex(rebar,ID) SNDMSG(rebar,RB_IDTOINDEX,ID,0)
#define Rebar_SetBandInfo(rebar,index,rbi) SNDMSG(rebar,RB_SETBANDINFO,index,(LPARAM)rbi)
#define Rebar_GetBandInfo(rebar,index,rbi) SNDMSG(rebar,RB_GETBANDINFO,index,(LPARAM)rbi)
#define Rebar_ShowBand(rebar,index,show) SNDMSG(rebar,RB_SHOWBAND,index,show)
#define Rebar_MoveBand(rebar,index,newIndex) SNDMSG(rebar,RB_MOVEBAND,index,newIndex)
#define Rebar_DeleteBand(rebar,index) SNDMSG(rebar,RB_DELETEBAND,index,0)
#define Rebar_SetBarInfo(rebar,ri) SNDMSG(rebar,RB_SETBARINFO,0,(LPARAM)ri)
#define Rebar_InsertBand(rebar,index,rbi) SNDMSG(rebar,RB_INSERTBAND,(WPARAM)index,(LPARAM)rbi)
#define Rebar_GetBandCount(rebar) SNDMSG(rebar,RB_GETBANDCOUNT,0,0)

#define ComboBoxEx_GetImageList(combobox) (HIMAGELIST)SNDMSG(combobox,CBEM_GETIMAGELIST,0,0)
#define ComboBoxEx_SetImageList(combobox,imageList) SNDMSG(combobox,CBEM_SETIMAGELIST,0,(LPARAM)imageList)
#define ComboBoxEx_InsertItem(combobox,cbei) SNDMSG(combobox,CBEM_INSERTITEM,0,(LPARAM)cbei)

#define ToolBar_CheckButton(toolbar,ID,check) SNDMSG(toolbar,TB_CHECKBUTTON,(WPARAM)ID,check)
#define ToolBar_EnableButton(toolbar,ID,enable) SNDMSG(toolbar,TB_ENABLEBUTTON,(WPARAM)ID,enable)
#define ToolBar_IsButtonChecked(toolbar,ID) (BOOL)SNDMSG(toolbar,TB_ISBUTTONCHECKED,(WPARAM)ID,0)
#define ToolBar_IsButtonEnabled(toolbar,ID) (BOOL)SNDMSG(toolbar,TB_ISBUTTONENABLED,(WPARAM)ID,0)
#define ToolBar_PressButton(toolbar,ID,press) SNDMSG(toolbar,TB_PRESSBUTTON,(WPARAM)ID,press)
#define ToolBar_HitTest(toolbar,point) (int)SNDMSG(toolbar,TB_HITTEST,0,(LPARAM)point)
#define ToolBar_GetButton(toolbar,index,tbb) SNDMSG(toolbar,TB_GETBUTTON,index,(LPARAM)tbb)
#define ToolBar_GetItemRect(toolbar,index,rect) SNDMSG(toolbar,TB_GETITEMRECT,index,(LPARAM)rect)
#define ToolBar_GetRect(toolbar,ID,rect) SNDMSG(toolbar,TB_GETRECT,ID,(LPARAM)rect)
#define ToolBar_ButtonCount(toolbar) (int)SNDMSG(toolbar,TB_BUTTONCOUNT,0,0)
#define ToolBar_GetButtonText(toolbar,ID,text) SNDMSG(toolbar,TB_GETBUTTONTEXT,ID,(LPARAM)text)
#define ToolBar_GetImageList(toolbar) (HIMAGELIST)SNDMSG(toolbar,TB_GETIMAGELIST,0,0)
#define ToolBar_GetDisabledImageList(toolbar) (HIMAGELIST)SNDMSG(toolbar,TB_GETDISABLEDIMAGELIST,0,0)
#define ToolBar_ButtonStructSize(toolbar,size) SNDMSG(toolbar,TB_BUTTONSTRUCTSIZE,(WPARAM)size,0)
#define ToolBar_AutoSize(toolbar) SNDMSG(toolbar,TB_AUTOSIZE,0,0)
#define ToolBar_LoadImages(toolbar,ID,instance) SNDMSG(toolbar,TB_LOADIMAGES,ID,(LPARAM)instance)
#define ToolBar_InsertButton(toolbar,index,tbb) SNDMSG(toolbar,TB_INSERTBUTTON,index,(LPARAM)tbb)
#define ToolBar_AddButtons(toolbar,count,tbb) SNDMSG(toolbar,TB_ADDBUTTONS,count,(LPARAM)tbb)
#define ToolBar_SetImageList(toolbar,imagelist) SNDMSG(toolbar,TB_SETIMAGELIST,0,(LPARAM)imagelist)
#define ToolBar_SetDisabledImageList(toolbar,imagelist) SNDMSG(toolbar,TB_SETDISABLEDIMAGELIST,0,(LPARAM)imagelist)
#define ToolBar_SetButtonSize(toolbar,x,y) SNDMSG(toolbar,TB_SETBUTTONSIZE,0,MAKELONG(x,y))
#define ToolBar_SetButtonInfo(toolbar,indexID,tbi) SNDMSG(toolbar,TB_SETBUTTONINFO,(WPARAM)indexID,(LPARAM)tbi)
#define ToolBar_SetBitmapSize(toolbar,x,y) SNDMSG(toolbar,TB_SETBITMAPSIZE,0,MAKELONG(x,y))
